### PR TITLE
Added possibility to configure proxy for PostmarkTransport (HttpSocket)

### PR DESCRIPTION
**Pull request by rozehnal**
Added simple possibility of configuring proxy for HttpSocket. It is safe and backwards compatible change.

A CakePHP configuration may look like:

```
<?php
class EmailConfig {

	public $postmark;

	public function __construct() {

		$this->postmark = array(
			'transport' => 'Postmark.Postmark',
			'uri' => POSTMARK_URI,
			'key' => POSTMARK_KEY,
			'proxy' => array(
				'host' => PROXY_HOST,
				'port' => PROXY_PORT,
			),
		);
    }
}
```

Thanks for any comment.

### CODE REVIEW

**Comment by maurymmarques** [comment]
Hi Rozehnal,
Thank you for your contribution.

Do we can change some little things?
[This part]( https://github.com/maurymmarques/postmark-cakephp/pull/13/files#diff-42ce3d246743d1e03ea437d1bb537e80R71) for this:

```php
// Configure transport
$this->__configure();
```

And [this one](https://github.com/maurymmarques/postmark-cakephp/pull/13/files#diff-42ce3d246743d1e03ea437d1bb537e80R97) for this:

```php
/**
 * Configure transport. 
 * Currently only proxy setting is supported.
 *
 * @return void
 */
	private function __configure() {
		// Host is mandatory part of a proxy configuration
		if (isset($this->_config['proxy']['host']) && !empty($this->_config['proxy']['host'])) {
			$default = array(
				'port' => 3128,
				'method' => null,
				'user' => null,
				'pass' => null
			);
			$params = array_merge($default, $this->_config['proxy']);
			$this->__postmarkConnection->configProxy($params['host'], $params['port'], $params['method'], $params['user'], $params['pass']);
		}
	}
```
Could you please do that?
Thank you.

**Comment by maurymmarques** [comment]
After your changes I'll add this part to the documentation (after [Configuration](https://github.com/maurymmarques/postmark-cakephp#configuration) and before [Usage](https://github.com/maurymmarques/postmark-cakephp#usage)):

### Proxy

You can also configure a proxy in the file `app/Config/email.php`:

```php
class EmailConfig {
  public $postmark = array(
    'transport' => 'Postmark.Postmark',
    'uri' => 'http://api.postmarkapp.com/email',
    'key' => 'your-postmark-key',
    'track_opens' => true,
    'proxy' => array(
      'host' => 'your-proxy-host', # Can be an array with settings to authentication class
      'port' => 3128, # Default 3128
      'method' => null, # Proxy method (ie, Basic, Digest). If empty, disable proxy authentication
      'user' => null, # Username if your proxy need authentication
      'pass' => null # Password to proxy authentication
    ),
  );
}
```

Read more about [HttpSocket Parameters](https://api.cakephp.org/2.7/class-HttpSocket.html#_configProxy)

**Comment by rozehnal** [comment]
Thanks! Good improvements. I updated documentation also in my commit.

**Comment by maurymmarques** [comment]
Thank you.

**Pull request merged**
